// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OrderManagement
{
    public partial class Order
    {
        public Order()
        {
            ProductOrder = new HashSet<ProductOrder>();
        }

        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public string UserId { get; set; }
        /// <summary>
        /// 1 = &apos;Placed&apos;, 2 = &apos;Approved&apos;, 3 = &apos;Cancelled&apos;,4=&apos;In transit &apos;, 5=&apos;Delivered&apos;
        /// </summary>
        public short OrderStatus { get; set; }
        public int ShippingAddressId { get; set; }
        public DateTime? OrderDate { get; set; }

        public virtual ShippingAddress ShippingAddress { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }

    public partial class ProductOrder
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }

        public virtual Order Order { get; set; }
    }

    public partial class ShippingAddress
    {
        public ShippingAddress()
        {
            Order = new HashSet<Order>();
        }

        public int ShippingAddressId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public decimal Pincode { get; set; }
        public string UserId { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }

    public class SubmitOrder 
    {
        public string[] OrdDetails { get; set; }
        public string UserID { get; set; }
    }
    
  }