// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OrderManagement.Models
{
    public partial class Products
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public int Sku { get; set; }
        public int AvailableQuantity { get; set; }
        public DateTime? Date { get; set; }
        public decimal Price { get; set; }
    }
}